
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Demo
* Id: 038587ec-2989-01aa-becb-3908833e756d
* 
* -------------------------------------------------------------------------------
**/

import type { IContentItem, IContentItemElements } from '@kontent-ai/delivery-sdk';
import type {
    ContentTypeCodenames,
    CollectionCodenames,
    LanguageCodenames,
    WorkflowCodenames,
    WorkflowStepCodenames
} from './delivery.codenames.ts';

/**
 * Core content type used in favor of generic 'IContentItem'
 */
export type CoreContentType<
    TElements extends IContentItemElements = IContentItemElements,
    TContentTypeCodename extends ContentTypeCodenames = ContentTypeCodenames
> = IContentItem<TElements, TContentTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>;
