
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Demo
* Id: 038587ec-2989-01aa-becb-3908833e756d
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = 'default';

/**
 * Type representing all content types
 */
export type ContentTypeCodenames = 'article' | 'video' | 'landing_page' | 'event';

/**
 * Type representing all collections
 */
export type CollectionCodenames = 'default';

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = 'default';

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames = 'draft' | 'published' | 'archived' | 'scheduled';

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
    | 'title'
    | 'introduction'
    | 'image'
    | 'body_copy'
    | 'publish_date'
    | 'headline'
    | 'description'
    | 'video_link'
    | 'caption'
    | 'autoplay'
    | 'subheadline'
    | 'hero_image'
    | 'featured_content'
    | 'name'
    | 'asset'
    | 'start_date'
    | 'end_date'
    | 'event_type'
    | 'event_topic';
