/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 */
export const contentTypes = {
  /**
   * Article
   */
  article: {
    codename: "article",
    id: "decfd6d7-5392-4740-bdb7-f689264713bb",
    externalId: undefined,
    name: "Article",
    elements: {
      /**
       * Body Copy (rich_text)
       */
      body_copy: {
        codename: "body_copy",
        id: "f538ae1c-2d68-40a8-91f8-f276b0237152",
        externalId: undefined,
        name: "Body Copy",
        required: false,
        type: "rich_text",
      },

      /**
       * Image (asset)
       */
      image: {
        codename: "image",
        id: "f9763b82-4733-4a4e-8aac-e695ea97412e",
        externalId: undefined,
        name: "Image",
        required: false,
        type: "asset",
      },

      /**
       * Introduction (text)
       */
      introduction: {
        codename: "introduction",
        id: "05ec475e-bb61-4572-8ce0-5eec942925dd",
        externalId: undefined,
        name: "Introduction",
        required: false,
        type: "text",
      },

      /**
       * Publish Date (date_time)
       */
      publish_date: {
        codename: "publish_date",
        id: "0e33b980-1d7a-405e-b02a-3ab76fcffc3b",
        externalId: undefined,
        name: "Publish Date",
        required: false,
        type: "date_time",
      },

      /**
       * Title (text)
       */
      title: {
        codename: "title",
        id: "6715c085-15e3-411f-adb6-94f2b08013cc",
        externalId: undefined,
        name: "Title",
        required: false,
        type: "text",
      },
    },
  },

  /**
   * Event
   */
  event: {
    codename: "event",
    id: "446d4c1e-5049-4e45-ae1c-4284e660fe68",
    externalId: undefined,
    name: "Event",
    elements: {
      /**
       * Asset (asset)
       */
      asset: {
        codename: "asset",
        id: "3e1b3668-0605-4f19-a689-a088448d49c0",
        externalId: undefined,
        name: "Asset",
        required: false,
        type: "asset",
      },

      /**
       * Description (rich_text)
       */
      description: {
        codename: "description",
        id: "a30856f6-4700-48ec-b009-f1b24f4b41c2",
        externalId: undefined,
        name: "Description",
        required: false,
        type: "rich_text",
      },

      /**
       * End Date (date_time)
       */
      end_date: {
        codename: "end_date",
        id: "c33d2553-e161-4b2f-81e2-43f06c945f08",
        externalId: undefined,
        name: "End Date",
        required: false,
        type: "date_time",
      },

      /**
       * Topics (taxonomy)
       */
      event_topic: {
        codename: "event_topic",
        id: "6ab84c72-0db5-4c09-88f8-d9bdefbc9849",
        externalId: undefined,
        name: "Event Topic",
        required: false,
        type: "taxonomy",
      },

      /**
       * Event Type (taxonomy)
       */
      event_type: {
        codename: "event_type",
        id: "b36909a0-b8f2-4f09-9676-795ea5ce49f7",
        externalId: undefined,
        name: "Event Type",
        required: false,
        type: "taxonomy",
      },

      /**
       * Name (text)
       */
      name: {
        codename: "name",
        id: "42ee07e2-3b03-4795-9843-da0731645a20",
        externalId: undefined,
        name: "Name",
        required: false,
        type: "text",
      },

      /**
       * Start date (date_time)
       */
      start_date: {
        codename: "start_date",
        id: "980d800f-cd12-43a0-ab4c-5c0e50cea0b9",
        externalId: undefined,
        name: "Start date",
        required: false,
        type: "date_time",
      },
    },
  },

  /**
   * Landing Page
   */
  landing_page: {
    codename: "landing_page",
    id: "9c8cf106-199f-4535-856b-a66e97399b42",
    externalId: undefined,
    name: "Landing Page",
    elements: {
      /**
       * Body Copy (rich_text)
       */
      body_copy: {
        codename: "body_copy",
        id: "d52b6c00-2b3d-4978-b5d8-f80703601f20",
        externalId: undefined,
        name: "Body Copy",
        required: false,
        type: "rich_text",
      },

      /**
       * Featured Content (modular_content)
       */
      featured_content: {
        codename: "featured_content",
        id: "3c1157eb-c8f0-4a2b-b434-023dff40e5d4",
        externalId: undefined,
        name: "Featured Content",
        required: false,
        type: "modular_content",
      },

      /**
       * Headline (text)
       */
      headline: {
        codename: "headline",
        id: "3c5fca8b-a024-42fe-b2ec-eb2d2f8e6ca8",
        externalId: undefined,
        name: "Headline",
        required: false,
        type: "text",
      },

      /**
       * Hero Image (asset)
       */
      hero_image: {
        codename: "hero_image",
        id: "9f33cab3-4496-489a-8b36-0a602b3b41a3",
        externalId: undefined,
        name: "Hero Image",
        required: false,
        type: "asset",
      },

      /**
       * Subheadline (text)
       */
      subheadline: {
        codename: "subheadline",
        id: "a19250b6-c8e1-4871-bf83-956e95782d7c",
        externalId: undefined,
        name: "Subheadline",
        required: false,
        type: "text",
      },
    },
  },

  /**
   * Video
   */
  video: {
    codename: "video",
    id: "fe811adb-4000-4563-b4f7-7d00371e820c",
    externalId: undefined,
    name: "Video",
    elements: {
      /**
       * Autoplay (multiple_choice)
       */
      autoplay: {
        codename: "autoplay",
        id: "66b1191c-9114-4c89-aec9-f54fcaaecb36",
        externalId: undefined,
        name: "Autoplay",
        required: false,
        type: "multiple_choice",
        options: {
          true: {
            name: "True",
            id: "c1a6aec5-64a6-4bd2-ac33-98d1acab0321",
            codename: "true",
            externalId: undefined,
          },
          false: {
            name: "False",
            id: "6a7d1345-0b3e-4c1f-b142-107e3a5f0f6a",
            codename: "false",
            externalId: undefined,
          },
        },
      },

      /**
       * Caption (text)
       */
      caption: {
        codename: "caption",
        id: "c93e998a-74f8-44ec-b071-bd2f9b21d561",
        externalId: undefined,
        name: "Caption",
        required: false,
        type: "text",
      },

      /**
       * Video Link (text)
       */
      video_link: {
        codename: "video_link",
        id: "bfaf2724-4821-40b8-a859-e44ddc68bebd",
        externalId: undefined,
        name: "Video Link",
        required: false,
        type: "text",
      },
    },
  },
} as const;
