/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 */
export const roles = {
    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '3cdc324e-4fcb-4bc5-a312-8bf89c3b0f1f',
        name: 'Project manager'
    }
} as const;
