/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 */
export const roles = {
  /**
   * Project manager
   */
  projectManager: {
    codename: "project-manager",
    id: "131e9d4e-63c9-45ec-94a3-e678fb676c9d",
    name: "Project manager",
  },
} as const;
