/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 */
export const taxonomies = {
    /**
     * Event Topic
     */
    event_topic: {
        codename: 'event_topic',
        id: 'c73d35c2-df63-53f5-a9e5-a8450b027704',
        externalId: 'event_topic',
        name: 'Event Topic',
        terms: {
            nutrition: {
                codename: 'nutrition',
                id: '33b8eafc-080f-51ac-8fd8-ddf043551dd3',
                externalId: 'event_topic_nutrition',
                name: 'Nutrition',
                terms: {}
            },
            physical_fitness: {
                codename: 'physical_fitness',
                id: 'b1e860df-6000-5db1-8e17-12362bc65bc0',
                externalId: 'event_topic_physical_fitness',
                name: 'Physical Fitness',
                terms: {}
            },
            preventative_care: {
                codename: 'preventative_care',
                id: '17ac481e-30ef-5021-92c5-c2e335b922ab',
                externalId: 'event_topic_preventative_care',
                name: 'Preventative Care',
                terms: {}
            }
        }
    },

    /**
     * Event Type
     */
    event_type: {
        codename: 'event_type',
        id: '54519543-3e87-541d-a060-1246d721db5e',
        externalId: 'event_type',
        name: 'Event Type',
        terms: {
            seminar: {
                codename: 'seminar',
                id: '922336e0-b82a-5589-ae5d-8a3bb426ad9a',
                externalId: 'event_type_seminar',
                name: 'Seminar',
                terms: {}
            },
            webinar: {
                codename: 'webinar',
                id: '3b9e5257-cdbb-50ad-85be-0e8986745cdf',
                externalId: 'event_type_webinar',
                name: 'Webinar',
                terms: {}
            },
            workshop: {
                codename: 'workshop',
                id: '707bb142-f7d5-574a-b0ba-63037c412d84',
                externalId: 'event_type_workshop',
                name: 'Workshop',
                terms: {}
            }
        }
    }
} as const;
