/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 */
export const taxonomies = {
  /**
   * Event Type
   */
  event_type: {
    codename: "event_type",
    id: "520444f4-df68-46de-87fb-51bc9587e81a",
    externalId: undefined,
    name: "Event Type",
    terms: {
      conference: {
        codename: "conference",
        id: "45916307-35dc-4f02-b339-d708550692fb",
        externalId: undefined,
        name: "Conference",
        terms: {},
      },
      seminar: {
        codename: "seminar",
        id: "deffa026-e95a-42ec-8bae-994895ea5ec6",
        externalId: undefined,
        name: "Seminar",
        terms: {},
      },
      webinar: {
        codename: "webinar",
        id: "554e5590-6c72-4e3e-9436-f505ac6b39af",
        externalId: undefined,
        name: "Webinar",
        terms: {},
      },
      workshop: {
        codename: "workshop",
        id: "1d2cac9b-fec2-437e-8760-d58739f97af6",
        externalId: undefined,
        name: "Workshop",
        terms: {},
      },
    },
  },

  /**
   * Topics
   */
  topics: {
    codename: "topics",
    id: "97a1eee0-2fa1-452d-a21b-6a113b38fad0",
    externalId: undefined,
    name: "Topics",
    terms: {
      nutrition: {
        codename: "nutrition",
        id: "bd4dadb0-8831-4c84-9003-53a52595ad54",
        externalId: undefined,
        name: "Nutrition",
        terms: {
          diabetes_management: {
            codename: "diabetes_management",
            id: "acd23424-2960-49f2-ae2d-e179f319d28b",
            externalId: undefined,
            name: "Diabetes Management",
            terms: {},
          },
          healthy_dieting: {
            codename: "healthy_dieting",
            id: "8b8d5b15-8b22-40b5-8777-e46a7b34a871",
            externalId: undefined,
            name: "Healthy Dieting",
            terms: {},
          },
        },
      },
      physical_fitness: {
        codename: "physical_fitness",
        id: "52777e64-5303-4d73-adde-7137e315c9bb",
        externalId: undefined,
        name: "Physical Fitness",
        terms: {
          cardio_exercise: {
            codename: "cardio_exercise",
            id: "d0e257a8-8aa5-4c2e-91c4-6d9884f1d122",
            externalId: undefined,
            name: "Cardio Exercise",
            terms: {},
          },
          strength_training: {
            codename: "strength_training",
            id: "f274178b-6ea5-4592-ae36-bde22214302e",
            externalId: undefined,
            name: "Strength Training",
            terms: {},
          },
        },
      },
      preventive_care: {
        codename: "preventive_care",
        id: "06954e24-3f28-4738-99ef-c85d8f42e88c",
        externalId: undefined,
        name: "Preventive Care",
        terms: {
          immunization: {
            codename: "immunization",
            id: "8b473c66-a69c-465f-ab69-f9a69bf4ecb4",
            externalId: undefined,
            name: "Immunization",
            terms: {},
          },
          screenings: {
            codename: "screenings",
            id: "fe180cd2-a0bd-42ec-bae9-0cda2e6f3373",
            externalId: undefined,
            name: "Screenings",
            terms: {},
          },
        },
      },
    },
  },
} as const;
