/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Event Topic
 * Id: c73d35c2-df63-53f5-a9e5-a8450b027704
 * Codename: event_topic
 */
export type EventTopic = 'nutrition' | 'physical_fitness' | 'preventative_care';
