
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-5'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 7cf79e13-fcde-01b6-f508-14ca05d794b8
* 
* -------------------------------------------------------------------------------
**/

/**
 * Event Type
 *
 * Codename: event_type
 * Id: 520444f4-df68-46de-87fb-51bc9587e81a
 */
export type EventType = 'conference' | 'seminar' | 'webinar' | 'workshop';
