/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Event Type
 * Id: 54519543-3e87-541d-a060-1246d721db5e
 * Codename: event_type
 */
export type EventType = 'seminar' | 'webinar' | 'workshop';
