
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Demo
* Id: 038587ec-2989-01aa-becb-3908833e756d
* 
* -------------------------------------------------------------------------------
**/

/**
 * Event Type
 *
 * Codename: event_type
 * Id: 520444f4-df68-46de-87fb-51bc9587e81a
 */
export type EventType = 'conference' | 'seminar' | 'webinar' | 'workshop';
