
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Demo
* Id: 038587ec-2989-01aa-becb-3908833e756d
* 
* -------------------------------------------------------------------------------
**/

/**
 * Event Topic
 *
 * Codename: event_topic
 * Id: 97a1eee0-2fa1-452d-a21b-6a113b38fad0
 */
export type EventTopic =
    | 'healthy_dieting'
    | 'diabetes_management'
    | 'nutrition'
    | 'cardio_exercise'
    | 'strength_training'
    | 'physical_fitness'
    | 'screenings'
    | 'immunization'
    | 'preventive_care';
