
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 7cf79e13-fcde-01b6-f508-14ca05d794b8
* 
* -------------------------------------------------------------------------------
**/

/**
 * Topics
 *
 * Codename: topics
 * Id: 97a1eee0-2fa1-452d-a21b-6a113b38fad0
 */
export type Topics =
    | 'healthy_dieting'
    | 'diabetes_management'
    | 'nutrition'
    | 'cardio_exercise'
    | 'strength_training'
    | 'physical_fitness'
    | 'screenings'
    | 'immunization'
    | 'preventive_care';
