
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 7cf79e13-fcde-01b6-f508-14ca05d794b8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.ts';

/**
 * Article
 *
 * Id: decfd6d7-5392-4740-bdb7-f689264713bb
 * Codename: article
 */
export type Article = CoreContentType<
    {
        /**
         * Title
         *
         * Type: text
         * Required: false
         * Codename: title
         * Id: 6715c085-15e3-411f-adb6-94f2b08013cc
         */
        readonly title: Elements.TextElement;
        /**
         * Introduction
         *
         * Type: text
         * Required: false
         * Codename: introduction
         * Id: 05ec475e-bb61-4572-8ce0-5eec942925dd
         */
        readonly introduction: Elements.TextElement;
        /**
         * Image
         *
         * Type: asset
         * Required: false
         * Codename: image
         * Id: f9763b82-4733-4a4e-8aac-e695ea97412e
         */
        readonly image: Elements.AssetsElement;
        /**
         * Body Copy
         *
         * Type: rich_text
         * Required: false
         * Codename: body_copy
         * Id: f538ae1c-2d68-40a8-91f8-f276b0237152
         */
        readonly body_copy: Elements.RichTextElement<CoreContentType>;
        /**
         * Publish Date
         *
         * Type: date_time
         * Required: false
         * Codename: publish_date
         * Id: 0e33b980-1d7a-405e-b02a-3ab76fcffc3b
         */
        readonly publish_date: Elements.DateTimeElement;
    },
    'article'
>;

/**
 * Type representing all available element codenames for Article
 */
export type ArticleElementCodenames = 'title' | 'introduction' | 'image' | 'body_copy' | 'publish_date';

/**
 * Type guard for Article
 */
export function isArticle(item: CoreContentType | undefined | null): item is Article {
    return item?.system?.type === 'article';
}
