import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Article
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 */
export type Article = IContentItem<{
    /**
     * Body Copy (rich_text)
     * Required: false
     * Id: 0747fb13-7383-59fe-bf64-2bab6d384279
     * Codename: body_copy
     */
    body_copy: Elements.RichTextElement;

    /**
     * Image (asset)
     * Required: false
     * Id: 8c501358-d0f7-5959-95bd-2991f1215e33
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Introduction (text)
     * Required: false
     * Id: c3fc1a88-5577-5130-b0aa-b1837c009ba6
     * Codename: introduction
     */
    introduction: Elements.TextElement;

    /**
     * Publish Date (date_time)
     * Required: false
     * Id: abdf08ea-55f0-5460-96e0-391f7471c7e9
     * Codename: publish_date
     */
    publish_date: Elements.DateTimeElement;

    /**
     * Title (text)
     * Required: false
     * Id: ad06c69a-9ccd-5d8c-b2de-b6a9f83d00fc
     * Codename: title
     */
    title: Elements.TextElement;
}>;
