
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Demo
* Id: 038587ec-2989-01aa-becb-3908833e756d
* 
* -------------------------------------------------------------------------------
**/

export * from './article.ts';
export * from './event.ts';
export * from './landingPage.ts';
export * from './video.ts';
