
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-11'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Demo
* Id: 038587ec-2989-01aa-becb-3908833e756d
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.ts';
import type { Video, Event, Article } from './index.ts';

/**
 * Landing Page
 *
 * Id: 9c8cf106-199f-4535-856b-a66e97399b42
 * Codename: landing_page
 */
export type LandingPage = CoreContentType<
    {
        /**
         * Headline
         *
         * Type: text
         * Required: false
         * Codename: headline
         * Id: 3c5fca8b-a024-42fe-b2ec-eb2d2f8e6ca8
         */
        readonly headline: Elements.TextElement;
        /**
         * Subheadline
         *
         * Type: text
         * Required: false
         * Codename: subheadline
         * Id: a19250b6-c8e1-4871-bf83-956e95782d7c
         */
        readonly subheadline: Elements.TextElement;
        /**
         * Hero Image
         *
         * Type: asset
         * Required: false
         * Codename: hero_image
         * Id: 9f33cab3-4496-489a-8b36-0a602b3b41a3
         */
        readonly hero_image: Elements.AssetsElement;
        /**
         * Body Copy
         *
         * Type: rich_text
         * Required: false
         * Codename: body_copy
         * Id: d52b6c00-2b3d-4978-b5d8-f80703601f20
         */
        readonly body_copy: Elements.RichTextElement<Video>;
        /**
         * Featured Content
         *
         * Type: modular_content
         * Required: false
         * Codename: featured_content
         * Id: 3c1157eb-c8f0-4a2b-b434-023dff40e5d4
         */
        readonly featured_content: Elements.LinkedItemsElement<Event | Article>;
    },
    'landing_page'
>;

/**
 * Type representing all available element codenames for Landing Page
 */
export type LandingPageElementCodenames = 'headline' | 'subheadline' | 'hero_image' | 'body_copy' | 'featured_content';

/**
 * Type guard for Landing Page
 */
export function isLandingPage(item: CoreContentType | undefined | null): item is LandingPage {
    return item?.system?.type === 'landing_page';
}
