import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Landing Page
 * Id: aa610b72-ca00-5ee3-bd30-f5b001b9d64e
 * Codename: landing_page
 */
export type LandingPage = IContentItem<{
    /**
     * Body Copy (rich_text)
     * Required: false
     * Id: b0e94942-8d23-5f67-aa72-15c0ed45a390
     * Codename: body_copy
     */
    body_copy: Elements.RichTextElement;

    /**
     * Featured Content (modular_content)
     * Required: false
     * Id: 7f939caa-a3a2-5018-a127-fe2938129fa9
     * Codename: featured_content
     */
    featured_content: Elements.LinkedItemsElement<IContentItem>;

    /**
     * Headline (text)
     * Required: false
     * Id: ff2c9d21-64f1-5d64-b650-344dd0ba44d2
     * Codename: headline
     */
    headline: Elements.TextElement;

    /**
     * Hero Image (asset)
     * Required: false
     * Id: efe09118-3de6-5581-b784-43408e2e673b
     * Codename: hero_image
     */
    hero_image: Elements.AssetsElement;

    /**
     * Subheadline (text)
     * Required: false
     * Id: 96fa63e6-2f46-557d-9dc8-4874ae9340a6
     * Codename: subheadline
     */
    subheadline: Elements.TextElement;
}>;
