import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@7.4.0'
 *
 * Solution
 * Id: f3df0cce-53f0-4ab1-875c-dd5c5d57a0ba
 * Codename: solution
 */
export type Solution = IContentItem<{
    /**
     * Headline (text)
     * Required: true
     * Id: 677e82da-9f88-49ca-9c73-2689709cbbdf
     * Codename: headline
     */
    headline: Elements.TextElement;

    /**
     * Image (asset)
     * Required: true
     * Id: 819f6844-4230-4ae1-ade7-ddb6e62ca7bd
     * Codename: image
     */
    image: Elements.AssetsElement;

    /**
     * Summary (text)
     * Required: true
     * Id: c588ca2a-5cac-47b3-897d-96995c17e1f8
     * Codename: summary
     */
    introduction: Elements.TextElement;
}>;
