
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0-5'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Kontent.ai Kickstart
* Environment: Production
* Id: 7cf79e13-fcde-01b6-f508-14ca05d794b8
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from '@kontent-ai/delivery-sdk';
import type { CoreContentType } from '../system/index.ts';

/**
 * Video
 *
 * Id: fe811adb-4000-4563-b4f7-7d00371e820c
 * Codename: video
 */
export type Video = CoreContentType<
    {
        /**
         * Headline
         *
         * Type: text
         * Required: false
         * Codename: headline
         * Id: 5e1bf371-2032-4e14-a074-a4803f1ee368
         */
        readonly headline: Elements.TextElement;
        /**
         * Description
         *
         * Type: text
         * Required: false
         * Codename: description
         * Id: 1824fdaa-4466-4abf-bd42-31aa3156444d
         */
        readonly description: Elements.TextElement;
        /**
         * Video Link
         *
         * Type: text
         * Required: false
         * Codename: video_link
         * Id: bfaf2724-4821-40b8-a859-e44ddc68bebd
         */
        readonly video_link: Elements.TextElement;
        /**
         * Caption
         *
         * Type: text
         * Required: false
         * Codename: caption
         * Id: c93e998a-74f8-44ec-b071-bd2f9b21d561
         */
        readonly caption: Elements.TextElement;
        /**
         * Autoplay
         *
         * Type: multiple_choice
         * Required: false
         * Codename: autoplay
         * Id: 66b1191c-9114-4c89-aec9-f54fcaaecb36
         */
        readonly autoplay: Elements.MultipleChoiceElement<'true' | 'false'>;
    },
    'video'
>;

/**
 * Type representing all available element codenames for Video
 */
export type VideoElementCodenames = 'headline' | 'description' | 'video_link' | 'caption' | 'autoplay';

/**
 * Type guard for Video
 */
export function isVideo(item: CoreContentType): item is Video {
    return item.system.type === 'video';
}
